/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package seller;

import Connection.myconnection;
import admin.AutoCompletion;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import login.RegisterPage;
import login.firstlogin;
import Connection.myconnection;
import static Connection.myconnection.con;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class seller_interface extends javax.swing.JFrame {

    /**
     * Creates new form seller_interface
     */
    public seller_interface() {
        initComponents();
        //AutoCompletion.enable(category);
        File selectedImageFIle = new File("D:\\Java swing\\icons_mysqlConnector\\icons\\Logout Rounded.png");
        String SelectedImagePath = selectedImageFIle.getAbsolutePath();
        ImageIcon ic = new ImageIcon(SelectedImagePath);
        Image image = ic.getImage().getScaledInstance(logout.getWidth(), logout.getHeight(), Image.SCALE_SMOOTH);
        logout.setIcon(new ImageIcon(image));
        
        selectedImageFIle = new File("D:\\Java swing\\icons_mysqlConnector\\icons\\menu.png");
        SelectedImagePath = selectedImageFIle.getAbsolutePath();
        ic = new ImageIcon(SelectedImagePath);
        image = ic.getImage().getScaledInstance(menu.getWidth(), menu.getHeight(), Image.SCALE_SMOOTH);
        menu.setIcon(new ImageIcon(image));
        
        selectedImageFIle = new File("D:\\Java swing\\icons_mysqlConnector\\icons\\menu.png");
        SelectedImagePath = selectedImageFIle.getAbsolutePath();
        ic = new ImageIcon(SelectedImagePath);
        image = ic.getImage().getScaledInstance(menu1.getWidth(), menu1.getHeight(), Image.SCALE_SMOOTH);
        menu1.setIcon(new ImageIcon(image));

        addTableHeader();
        
        
    }
    String supplier_name = "Apple";
    public seller_interface(String s) {
        initComponents();
        addTableHeader();
        username.setText(s);
        supplier_name = s;
        username.setText(s);
        File selectedImageFIle = new File("D:\\Java swing\\icons_mysqlConnector\\icons\\Logout Rounded.png");
        String SelectedImagePath = selectedImageFIle.getAbsolutePath();
        ImageIcon ic = new ImageIcon(SelectedImagePath);
        Image image = ic.getImage().getScaledInstance(logout.getWidth(), logout.getHeight(), Image.SCALE_SMOOTH);
        logout.setIcon(new ImageIcon(image));
        
        selectedImageFIle = new File("D:\\Java swing\\icons_mysqlConnector\\icons\\menu.png");
        SelectedImagePath = selectedImageFIle.getAbsolutePath();
        ic = new ImageIcon(SelectedImagePath);
        image = ic.getImage().getScaledInstance(menu.getWidth(), menu.getHeight(), Image.SCALE_SMOOTH);
        menu.setIcon(new ImageIcon(image));
        
        selectedImageFIle = new File("D:\\Java swing\\icons_mysqlConnector\\icons\\menu.png");
        SelectedImagePath = selectedImageFIle.getAbsolutePath();
        ic = new ImageIcon(SelectedImagePath);
        image = ic.getImage().getScaledInstance(menu1.getWidth(), menu1.getHeight(), Image.SCALE_SMOOTH);
        menu1.setIcon(new ImageIcon(image));

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        red_invoker = new javax.swing.JButton();
        blue_invoker = new javax.swing.JButton();
        grren_invoker = new javax.swing.JButton();
        menu = new javax.swing.JLabel();
        mother_panel = new javax.swing.JPanel();
        red = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        browse = new javax.swing.JButton();
        icon = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cate = new javax.swing.JTextField();
        blue = new javax.swing.JPanel();
        green = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        menu1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(47, 60, 126));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(215, 500));

        red_invoker.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        red_invoker.setText("Add Product");
        red_invoker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                red_invokerMouseClicked(evt);
            }
        });
        red_invoker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                red_invokerActionPerformed(evt);
            }
        });

        blue_invoker.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        blue_invoker.setText("Work In Process");
        blue_invoker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blue_invokerMouseClicked(evt);
            }
        });
        blue_invoker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blue_invokerActionPerformed(evt);
            }
        });

        grren_invoker.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        grren_invoker.setText("Work In Process");
        grren_invoker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grren_invokerActionPerformed(evt);
            }
        });

        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(red_invoker, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blue_invoker, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grren_invoker, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addComponent(red_invoker, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blue_invoker, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(grren_invoker, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, -1));

        mother_panel.setLayout(new java.awt.CardLayout());

        red.setBackground(new java.awt.Color(251, 234, 235));
        red.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Product Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quantity Available");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Price");
        jLabel4.setPreferredSize(new java.awt.Dimension(24, 16));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        name.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N

        quantity.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N

        price.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Image");
        jLabel5.setPreferredSize(new java.awt.Dimension(24, 16));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("REMOVE");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        browse.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        browse.setText("Browse //");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });

        icon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        icon.setForeground(new java.awt.Color(51, 51, 51));
        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setText("Image goes here");
        icon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Category");

        cate.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        cate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout redLayout = new javax.swing.GroupLayout(red);
        red.setLayout(redLayout);
        redLayout.setHorizontalGroup(
            redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redLayout.createSequentialGroup()
                        .addGroup(redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(redLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(redLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12)
                                .addGroup(redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(quantity)
                                    .addComponent(cate, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(redLayout.createSequentialGroup()
                        .addGroup(redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(redLayout.createSequentialGroup()
                        .addGroup(redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(redLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(browse))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        redLayout.setVerticalGroup(
            redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redLayout.createSequentialGroup()
                .addGroup(redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addGroup(redLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redLayout.createSequentialGroup()
                                .addComponent(browse)
                                .addGap(58, 58, 58)))
                        .addGap(17, 17, 17)
                        .addGroup(redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton4))
                        .addGap(54, 54, 54)))
                .addContainerGap())
        );

        mother_panel.add(red, "card2");

        blue.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout blueLayout = new javax.swing.GroupLayout(blue);
        blue.setLayout(blueLayout);
        blueLayout.setHorizontalGroup(
            blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 917, Short.MAX_VALUE)
        );
        blueLayout.setVerticalGroup(
            blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        mother_panel.add(blue, "card2");

        green.setBackground(new java.awt.Color(51, 255, 51));
        green.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout greenLayout = new javax.swing.GroupLayout(green);
        green.setLayout(greenLayout);
        greenLayout.setHorizontalGroup(
            greenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        greenLayout.setVerticalGroup(
            greenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        mother_panel.add(green, "card2");

        getContentPane().add(mother_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(251, 234, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/account_dark.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 40, 30));

        username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(51, 51, 51));
        username.setText("XYZ");
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 50, 30));

        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout_1.png"))); // NOI18N
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 37, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LOGOUT");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 0, 910, -1));

        jLabel9.setBackground(new java.awt.Color(47, 60, 126));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Seller Dashboard");
        jLabel9.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 215, -1));

        jPanel6.setBackground(new java.awt.Color(251, 234, 235));

        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addGap(0, 170, Short.MAX_VALUE)
                    .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 420, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 44, 220, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    String SelectedImagePath = "";
    String names = "";
    String ids = "";
    String quantitys = "";
    String prices = "";
    
    public void addTableHeader() {
        DefaultTableModel model;
        model = (DefaultTableModel) jTable1.getModel();
        Object[] newIdentifiers = new Object[]{"Product Name", "Quantity Available", "Price", "Picture"};
        model.setColumnIdentifiers(newIdentifiers);
        jTable1.getColumn("Picture").setCellRenderer(new myTableCellRenderer());
    }
    
    
    class myTableCellRenderer implements TableCellRenderer {

        @Override
        
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column)
        {
            jTable1.setRowHeight(60);
            
            return (Component) value;
            
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        JLabel label_image = new JLabel();
        ImageIcon imageicon = new ImageIcon(SelectedImagePath);
        Image IIC = imageicon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
        label_image.setIcon(new ImageIcon(IIC));

        if (name.getText().equals("") || quantity.getText().equals("") || price.getText().equals("")) {
            JOptionPane.showMessageDialog(new JFrame(), "Please Complete all the fields", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
            names = name.getText();
            quantitys = quantity.getText();
            prices = price.getText();
            table.addRow(new Object[]{ names, quantitys, prices, label_image});
            // image_label.remove(imageicon);
            int id = 1;
            ResultSet rs;
            try {
                 Connection con = (Connection) myconnection.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("select * from product_info");
                rs = ps.executeQuery();
                while (rs.next()) {
                    id++;
                }
                id++;
                System.out.print(id);
            } catch (SQLException ex) {
                Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
            
            try {
                Connection con = (Connection) myconnection.getConnection();
                PreparedStatement ps2;
                Icon icon = label_image.getIcon();
                String sql2 = "INSERT INTO product_info values(?,?,?,?,?,?,?)";
                ps2 = con.prepareStatement(sql2);
                ps2.setInt(1, id);
                ps2.setString(2, name.getText());
                ps2.setString(3, cate.getText());
                ps2.setInt(4,Integer.parseInt(quantity.getText()) );
                
                ps2.setFloat(5, Float. parseFloat(price.getText()));
                ps2.setString(6, supplier_name);
                BufferedImage bi = new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB);
                Graphics g = bi.createGraphics();
                icon.paintIcon(null, g, 0, 0);
                g.dispose();
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                try {
                    ImageIO.write(bi, "png", baos);
                } catch (IOException ex) {

                }
                InputStream imgStream = new ByteArrayInputStream(baos.toByteArray());
                ps2.setBinaryStream(7, imgStream);
                if (ps2.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(new JFrame(), "Information added", "Dialog",
                            JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException ex) {
                Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, null, ex);
            }
            name.setText("");
            quantity.setText("");
            price.setText("");
            icon.setIcon(null);
            SelectedImagePath = "";
            
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser("D:\\Java swing\\icons_mysqlConnector\\icons");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("Images", "Png", "Jpeg", "Jpg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogoue = browseImageFile.showOpenDialog(null);
        if (showOpenDialogoue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFIle = browseImageFile.getSelectedFile();
            SelectedImagePath = selectedImageFIle.getAbsolutePath();
            ImageIcon ic = new ImageIcon(SelectedImagePath);
            Image image = ic.getImage().getScaledInstance(icon.getWidth(), icon.getHeight(), Image.SCALE_SMOOTH);
            icon.setIcon(new ImageIcon(image));
            
        }
    }//GEN-LAST:event_browseActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();

        if(name.getText().equals(""))
        {
            String val2 = name.getText();
            String val3 = quantity.getText();
            String val4 = price.getText();
            JLabel label_image = new JLabel();
            ImageIcon imageicon = new ImageIcon(SelectedImagePath);
            Image IIC = imageicon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
            label_image.setIcon(new ImageIcon(IIC));
            table.addRow(new Object[]{val2, val3, val4, label_image});
            icon.setIcon(null);
            
            table.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
            
        if(name.getText().equals(""))
        {
            JOptionPane.showMessageDialog(new JFrame(), "Secelct a row!", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(table.getRowCount() == 0)
        {
            
            JOptionPane.showMessageDialog(new JFrame(), "Insert a row first!", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            
            table.removeRow(jTable1.getSelectedRow());
            
            name.setText("");
            quantity.setText("");
            price.setText("");
            icon.setIcon(null);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
            
        if(table.getRowCount() == 0)
        {
            
            JOptionPane.showMessageDialog(new JFrame(), "Insert a row first!", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            int x = table.getRowCount();
            for(int i=0; i<x;i++)
            {
                table.removeRow(0);
            }
            
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new firstlogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void grren_invokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grren_invokerActionPerformed
        // TODO add your handling code here:
        mother_panel.removeAll();
        mother_panel.repaint();
        mother_panel.revalidate();

        mother_panel.add(green);
        mother_panel.repaint();
        mother_panel.revalidate();
    }//GEN-LAST:event_grren_invokerActionPerformed

    private void blue_invokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blue_invokerActionPerformed
        // TODO add your handling code here:
        mother_panel.removeAll();
        mother_panel.repaint();
        mother_panel.revalidate();

        mother_panel.add(blue);
        mother_panel.repaint();
        mother_panel.revalidate();
    }//GEN-LAST:event_blue_invokerActionPerformed

    private void blue_invokerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blue_invokerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_blue_invokerMouseClicked

    private void red_invokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_red_invokerActionPerformed
        // TODO add your handling code here:
        mother_panel.removeAll();
        mother_panel.repaint();
        mother_panel.revalidate();

        mother_panel.add(red);
        mother_panel.repaint();
        mother_panel.revalidate();
    }//GEN-LAST:event_red_invokerActionPerformed

    private void red_invokerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_invokerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_red_invokerMouseClicked

    int x = 210;
    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        // TODO add your handling code here:
        if(x==210)
        {
            jPanel2.setSize(215,470);
            Thread th=new Thread(){
            public void run(){
        try{
            for(int i=210;i>=0;i--){
            Thread.sleep(1);
            jPanel2.setSize(i,552);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    };th.start();
    x=0;
}
    }//GEN-LAST:event_menuMouseClicked

    private void menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseClicked
        // TODO add your handling code here:
        
        if(x==0){
            jPanel2.show();
            jPanel2.setSize(220,552);
            Thread th=new Thread(){
        public void run(){
            try{
                for(int i=0;i<=220;i++){
                    Thread.sleep(1);
                    jPanel2.setSize(i,552);
                }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
    }
    };th.start();
    x=210;
}
    }//GEN-LAST:event_menu1MouseClicked

    private void cateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seller_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seller_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seller_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seller_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seller_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blue;
    private javax.swing.JButton blue_invoker;
    private javax.swing.JButton browse;
    private javax.swing.JTextField cate;
    private javax.swing.JPanel green;
    private javax.swing.JButton grren_invoker;
    private javax.swing.JLabel icon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel menu1;
    private javax.swing.JPanel mother_panel;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JPanel red;
    private javax.swing.JButton red_invoker;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
