/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import Connection.myconnection;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import login.RegisterPage;

/**
 *
 * @author Dell
 */

public class customer_profile extends javax.swing.JFrame {

    /**
     * Creates new form customer_profile
     */
    String email_address;
    public customer_profile() {
        initComponents();
    }
    public customer_profile(String email) {
        initComponents();
        email_address = email;
        ResultSet rs;
        try {
            Connection con = (Connection) myconnection.getConnection();
            PreparedStatement ps;
            ps = con.prepareStatement("select * from customer_information where EMAIL = ?");
            ps.setString(1, email);
            rs = ps.executeQuery();
            if(rs.next())
            {
            name_label.setText(rs.getString(1));
            name.setText(rs.getString(1));
            user_email.setText(rs.getString(2));
            location.setText(rs.getString(6));
            phone.setText(rs.getString(4));
            gender.setText(rs.getString(7));
            String SelectedImagePath = rs.getString(5);
            ImageIcon ic = new ImageIcon(SelectedImagePath);
            Image image = ic.getImage().getScaledInstance(profile_picture.getWidth(), profile_picture.getHeight(), Image.SCALE_SMOOTH);
            profile_picture.setIcon(new ImageIcon(image));
            name.setEditable(false);
            //name.setCursor();
            }
            else
            {
                name_label.setText("not found");
                
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(RegisterPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        my_profile = new javax.swing.JScrollPane();
        my_profile1 = new javax.swing.JPanel();
        profile_picture = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        user_email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        birthdate = new javax.swing.JTextField();
        my_orders = new javax.swing.JScrollPane();
        my_profile2 = new javax.swing.JPanel();
        kart = new javax.swing.JScrollPane();
        my_profile3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1082, 695));

        jPanel10.setBackground(new java.awt.Color(255, 51, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/GOKARTGO.gif.gif"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Back");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 50, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Logout");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 60, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Kart");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 50, 30));

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new java.awt.CardLayout());

        my_profile.setBackground(new java.awt.Color(255, 250, 250));
        my_profile.setHorizontalScrollBar(null);

        my_profile1.setBackground(new java.awt.Color(255, 250, 250));
        my_profile1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        my_profile1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile_picture.setBackground(new java.awt.Color(0, 0, 0));
        profile_picture.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        profile_picture.setOpaque(true);
        my_profile1.add(profile_picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 59, 334, 300));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel8.setText("Welcome,");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        my_profile1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 107, 62));

        name_label.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        name_label.setText("Name");
        name_label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        my_profile1.add(name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 6, 135, 62));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Name");
        my_profile1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 377, 100, 27));

        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name.setText("jTextField1");
        name.setCaretColor(new java.awt.Color(255, 255, 255));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        my_profile1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 377, 190, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Email Address");
        my_profile1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 410, 100, 27));

        user_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        user_email.setText("jTextField1");
        user_email.setCaretColor(new java.awt.Color(255, 255, 255));
        my_profile1.add(user_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 190, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Location");
        my_profile1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 443, 100, 27));

        location.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        location.setText("jTextField1");
        my_profile1.add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 443, 190, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Phone Number");
        my_profile1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 476, 100, 27));

        phone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phone.setText("jTextField1");
        my_profile1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 476, 190, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Gender");
        my_profile1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 509, 100, 27));

        gender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gender.setText("jTextField1");
        my_profile1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 509, 190, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Birthdate");
        my_profile1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 548, 100, 27));

        birthdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        birthdate.setText("22 Jan, 2002");
        birthdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdateActionPerformed(evt);
            }
        });
        my_profile1.add(birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 548, 190, -1));

        my_profile.setViewportView(my_profile1);

        jPanel1.add(my_profile, "card5");

        my_orders.setBackground(new java.awt.Color(255, 250, 250));

        my_profile2.setBackground(new java.awt.Color(255, 250, 250));
        my_profile2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout my_profile2Layout = new javax.swing.GroupLayout(my_profile2);
        my_profile2.setLayout(my_profile2Layout);
        my_profile2Layout.setHorizontalGroup(
            my_profile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        my_profile2Layout.setVerticalGroup(
            my_profile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        my_orders.setViewportView(my_profile2);

        jPanel1.add(my_orders, "card5");

        kart.setBackground(new java.awt.Color(255, 250, 250));

        my_profile3.setBackground(new java.awt.Color(255, 250, 250));
        my_profile3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout my_profile3Layout = new javax.swing.GroupLayout(my_profile3);
        my_profile3.setLayout(my_profile3Layout);
        my_profile3Layout.setHorizontalGroup(
            my_profile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        my_profile3Layout.setVerticalGroup(
            my_profile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        kart.setViewportView(my_profile3);

        jPanel1.add(kart, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new login.firstlogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new admin.User(email_address).setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new Kart(email_address).setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void birthdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer_profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birthdate;
    private javax.swing.JTextField gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane kart;
    private javax.swing.JTextField location;
    private javax.swing.JScrollPane my_orders;
    private javax.swing.JScrollPane my_profile;
    private javax.swing.JPanel my_profile1;
    private javax.swing.JPanel my_profile2;
    private javax.swing.JPanel my_profile3;
    private javax.swing.JTextField name;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel profile_picture;
    private javax.swing.JTextField user_email;
    // End of variables declaration//GEN-END:variables
}
