/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin;

/**
 *
 * @author Administrator
 */

import java.util.ArrayList;
import javax.swing.JScrollBar;
import Connection.myconnection;
import customize.ScrollBarCustom;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;



public class Donation extends javax.swing.JPanel {

    
    DonationView jblist = null;

    public Donation() {
        
        initComponents();
        set_job_combo();
        update_list();
        
        JScrollBar verticalScrollBar = ScrollView.getVerticalScrollBar();
        verticalScrollBar.setUnitIncrement(20);
        verticalScrollBar.setBlockIncrement(200);
        ScrollView.setVerticalScrollBar(new ScrollBarCustom());

    }

    public void set_job_combo() {
        jt.removeAll();
        jt.addItem("");
        try {
            Connection con = myconnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT DISTINCT Location FROM donation");
            while (rs.next()) {
                jt.addItem(rs.getString("Location"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        jt1.removeAll();
        jt1.addItem("");
        try {
            Connection con = myconnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT DISTINCT Type FROM donation");
            while (rs.next()) {
                jt1.addItem(rs.getString("Type"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void update_list() {
    String JT = (String) (jt.getSelectedIndex() == -1 ? "" : jt.getItemAt(jt.getSelectedIndex()));
    String JT1 = (String) (jt1.getSelectedIndex() == -1 ? "" : jt1.getItemAt(jt1.getSelectedIndex()));
    //String SKL = skl.getText();
    if(JT.equals("none")) JT="";
    if(JT1.equals("none")) JT1="";
    String CMP = tf.getText();
   // String LCTN = lctn.getText();
    var jobs = new ArrayList<donationinfo>();

    try {
        Connection con = myconnection.getConnection();
        String query = "SELECT * FROM donation WHERE Location LIKE ? AND Type LIKE ? AND Donator_Company_Name LIKE ? ORDER BY Location ASC";
        var st = con.prepareStatement(query);
        st.setString(1, JT.equals("") ? "%" : "%" + JT + "%");
        st.setString(2, JT1.equals("") ? "%" : "%" + JT1 + "%");
        st.setString(3, CMP.equals("") ? "%" : "%" + CMP + "%");
       

        var rs = st.executeQuery();
        while (rs.next()) {
            jobs.add(new donationinfo(rs));
        }
        update_res_panel(new DonationView(jobs));
    } catch (Exception e) {
        e.printStackTrace();
    }
}


    public void update_res_panel(DonationView bv) {
        if (jblist != null) {
            ScrollView.getViewport().remove(jblist);
        }
        ScrollView.getViewport().add(bv);
        this.validate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollView = new javax.swing.JScrollPane();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        tf = new customize.TextField();
        jTextField7 = new javax.swing.JTextField();
        jt = new customize.ComboBoxSuggestion();
        jTextField9 = new javax.swing.JTextField();
        jt1 = new customize.ComboBoxSuggestion();
        rSMaterialButtonCircle1 = new necesario.RSMaterialButtonCircle();

        setBackground(new java.awt.Color(255, 255, 250));

        ScrollView.setBackground(new java.awt.Color(250, 250, 255));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 102, 0));
        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("SEARCH BY");

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 102, 0));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("Donation Company Name");

        tf.setLabelText("");

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 102, 0));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("LOCATION");

        jt.setName(""); // NOI18N

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 102, 0));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("Donation Type");

        jt1.setBackground(new java.awt.Color(255, 250, 250));
        jt1.setName(""); // NOI18N

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(255, 102, 0));
        rSMaterialButtonCircle1.setBorder(null);
        rSMaterialButtonCircle1.setText("Filter");
        rSMaterialButtonCircle1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7)
                    .addComponent(jt, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(jt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
            .addComponent(jTextField5)
            .addGroup(layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(rSMaterialButtonCircle1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(ScrollView)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(rSMaterialButtonCircle1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollView, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        // TODO add your handling code here:
        update_list();
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollView;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private customize.ComboBoxSuggestion jt;
    private customize.ComboBoxSuggestion jt1;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private customize.TextField tf;
    // End of variables declaration//GEN-END:variables
}
