/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import Connection.myconnection;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import login.RegisterPage;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Dell
 */
public class print extends javax.swing.JFrame {

    /**
     * Creates new form print
     */
    int total = 0;
    public print() {
        initComponents();
        setTime();
        fill_the_table();
        jTextArea1.setVisible(false);
        jScrollPane2.setVisible(false);
    }
    public void fill_the_table() {
        ResultSet rs;
        String s = "**********GOKARTGO**********\n\n";
        try {
            Connection con = (Connection) myconnection.getConnection();
            PreparedStatement ps;
            ps = con.prepareStatement("select * from kart");
            rs = ps.executeQuery();
            while (rs.next()) {
                int id = rs.getInt(1);
                String Product_Name = rs.getString(2);
                String Price = rs.getString(3);
                String Quantity = rs.getString(4);

                String tbdata[] = {Product_Name, Price, Quantity, String.valueOf(rs.getInt(3) * rs.getInt(4))};
                DefaultTableModel tblmodel = (DefaultTableModel) jTable1.getModel();
                tblmodel.addRow(tbdata);
                s += "Product Name: ";
                s += rs.getString(2);
                s += "   ";
                s += "Quantity: ";
                s += rs.getString(4);
                s += "   ";
                s += "Total Price: ";
                s += String.valueOf(rs.getInt(4) * rs.getInt(3));
                total += rs.getInt(4) * rs.getInt(3);
                s += "\n";
            }
            jTextArea1.setText(s);
        } catch (SQLException ex) {
            Logger.getLogger(RegisterPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = (Connection) myconnection.getConnection();
            PreparedStatement ps5;
            ps5 = con.prepareStatement("delete from kart");
            ps5.execute();
        } catch (SQLException ex) {
            Logger.getLogger(print.class.getName()).log(Level.SEVERE, "kart", ex);
        }
        total_price.setText(String.valueOf(total));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelToPrint = new javax.swing.JPanel();
        jdate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        total_price = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        rSMaterialButtonCircle1 = new necesario.RSMaterialButtonCircle();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jtime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelToPrint.setBackground(new java.awt.Color(255, 102, 51));
        panelToPrint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdate.setBackground(new java.awt.Color(255, 255, 255));
        jdate.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jdate.setToolTipText("");
        jdate.setOpaque(true);
        panelToPrint.add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 170, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("---------------------------------------------------------------------------------");
        panelToPrint.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 440, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("---------------------------------------------------------------------------------");
        panelToPrint.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 440, -1));

        jTable1.setFont(new java.awt.Font("Century", 1, 8)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT NAME", "TYPE", "PRICE", "QUANTITY", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(jTable1);

        panelToPrint.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 470, 180));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setText("Total");
        panelToPrint.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 120, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        panelToPrint.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 460, 20));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setText("****RECEIPT***");
        panelToPrint.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 230, 80));

        jLabel10.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel10.setText("BDT");
        panelToPrint.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        total_price.setBackground(new java.awt.Color(255, 255, 255));
        total_price.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        total_price.setOpaque(true);
        panelToPrint.add(total_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 110, 30));
        panelToPrint.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 310, 30));

        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        panelToPrint.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 30, 30));

        jLabel15.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jLabel15.setText("Order Date & Time:");
        panelToPrint.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel16.setText("THANK YOU!");
        panelToPrint.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 160, 50));

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(0, 255, 255));
        rSMaterialButtonCircle1.setBorder(null);
        rSMaterialButtonCircle1.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonCircle1.setText("GET RECEIPT");
        rSMaterialButtonCircle1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rSMaterialButtonCircle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle1MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        panelToPrint.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 210, 80));

        jTextArea1.setBackground(new java.awt.Color(255, 102, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 102, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("lkjglkjf\n");
        jScrollPane2.setViewportView(jTextArea1);

        panelToPrint.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 6, 360, 60));

        jtime.setBackground(new java.awt.Color(255, 255, 255));
        jtime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtime.setOpaque(true);
        panelToPrint.add(jtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelToPrint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelToPrint, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        new User().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    private void rSMaterialButtonCircle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1MouseClicked
        // TODO add your handling code here:
       
            try {
                jTextArea1.print();
            } catch (PrinterException e) {

            }
        dispose();
    }//GEN-LAST:event_rSMaterialButtonCircle1MouseClicked

    
    public void setTime() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {

                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(print.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Date date = new Date();
                    SimpleDateFormat tf = new SimpleDateFormat("hh:mm:ss aa");
                    SimpleDateFormat df = new SimpleDateFormat("EEEE,dd-MM-YYYY");
                    String time = tf.format(date);
                    jtime.setText(time.split(" ")[0] + " " + time.split(" ")[1]);
                    jdate.setText(df.format(date));
                }
            }
        }).start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jdate;
    private javax.swing.JLabel jtime;
    private javax.swing.JPanel panelToPrint;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private javax.swing.JLabel total_price;
    // End of variables declaration//GEN-END:variables
}
